In [26]:
import numpy as np

#yc1
n = 12
min_value = 0
max_value = 100

matrix = np.random.randint(min_value, max_value + 1, size=(n, n))

print(matrix)
print("Kiểu dữ liệu của phần tử trong ma trận:", matrix.dtype)
print("Kích thước mảng ma trận:", matrix.shape)
print("Số phần tử trong mảng ma trận:", matrix.size)
print("Số chiều trong mảng ma trận:", matrix.ndim)
print("--------------------------------------------")
#yc2
v_chinh = [matrix[i][i] for i in range(n)]
v_phu = [matrix[i][n - 1 - i] for i in range(n)]

print("Vector các phần tử nằm trên đường chéo chính:", v_chinh)
print("Vector các phần tử nằm trên đường chéo phụ:", v_phu)
print("--------------------------------------------")
#yc3
x = int(input("Nhập vào giá trị x (0-100): "))
equal_count = np.sum(matrix == x)
greater_count = np.sum(matrix > x)
smaller_count = np.sum(matrix < x)

print("1.Số phần tử có giá trị bằng x trong ma trận:", equal_count)
print("3.Số phần tử nhỏ hơn giá trị x trong ma trận:", smaller_count)
print("2.Số phần tử lớn hơn giá trị x trong ma trận:", greater_count)

[[  9  12  31  21  55  78  14  15  47  75   5  16]
 [ 46  39   1  86  83   6  73  50  90  50  90  78]
 [ 83  60  92  69  11  76  40  93   2  61 100  39]
 [  3  69   0  52  28  48  48  22  45  93  53  48]
 [ 60  91  66  15  19  28  97  43  94  89  69   8]
 [ 89  76  81  96   4  25   7  52  89  22  38  24]
 [ 61  22   3   8   6  99  98  98  96  24  25 100]
 [ 19  50  96  79  50   3  18  37  72  19  72  29]
 [ 39  89  90  79  88  70  21  44  25  65  81  50]
 [ 44  14  53  76  90  28 100  96  90  21  49  60]
 [ 29  76  78  59  19  59  59  83  95  27  22  26]
 [ 99  75  89  22  11  70  64  71  29  98  70  73]]
Kiểu dữ liệu của phần tử trong ma trận: int32
Kích thước mảng ma trận: (12, 12)
Số phần tử trong mảng ma trận: 144
Số chiều trong mảng ma trận: 2
--------------------------------------------
Vector các phần tử nằm trên đường chéo chính: [9, 39, 92, 52, 19, 25, 98, 37, 25, 21, 22, 73]
Vector các phần tử nằm trên đường chéo phụ: [16, 90, 61, 45, 43, 7, 99, 50, 79, 53, 76, 99]
----------