In [3]:
import numpy as np
diem_2a = np.loadtxt("Diem_2A.txt", delimiter="," ,dtype="float")
np.set_printoptions(linewidth=100)
print(diem_2a)

#yc1
def yc1(diem_2a):
    print("\n")
    dtb = np.array([])
    for i in range(0,diem_2a.shape[1]):
        dtb = np.append(dtb,diem_2a[:,i].mean())
    print("Điểm TB của từng học sinh trong lớp: ", dtb)
    print("-----------------------------------------------------------------------")
    print("Điểm TB cao nhất:", dtb.max())
    print("Của học sinh thứ:", np.argmax(dtb))
    print("Bảng điểm đầy đủ của học sinh", diem_2a[:,np.argmax(dtb)])
    print("-----------------------------------------------------------------------")
    print("Điểm TB thấp nhất:", dtb.min())
    print("Của học sinh thứ:", np.argmin(dtb))
    print("Bảng điểm đầy đủ của học sinh", diem_2a[:,np.argmin(dtb)])

#yc2
def yc2(diem_2a):
    print("\n")
    dtb = np.array([])
    for i in range(0,diem_2a.shape[0]):
        dtb = np.append(dtb,diem_2a[i,:].mean())
    print("Điểm TB của từng môn học:", dtb)
    print("-----------------------------------------------------------------------")
    print("Điểm TB cao nhất của môn học:",  dtb.max())
    print("Môn học thứ:", np.argmax(dtb))
    print("Bảng điểm đầy đủ của môn học", diem_2a[np.argmax(dtb),:])
    print("-----------------------------------------------------------------------")
    print("Điểm TB thấp nhất của môn học:", dtb.min())
    print("Môn học thứ:", np.argmin(dtb))
    print("Bảng điểm đầy đủ của môn học",diem_2a[ np.argmin(dtb),:])

#yc3
def yc3(diem_2a):
    print("\n")
    max = 0
    min = 0
    for i in range(0,diem_2a.shape[1]):
        if(diem_2a[:,i].std() > diem_2a[:,max].std()):
            max = i 
        if(diem_2a[:,i].std() < diem_2a[:,min].std()):
            min = i
    print("Học sinh học đồng đều nhất: [", min, "]",sep="")
    print("Bảng điểm của học sinh học đồng đều: ",diem_2a[:,min])
    print("-----------------------------------------------------------------------")
    print("Học sinh học lệch nhất: [", max, "]",sep="")
    print("Bảng điểm của học sinh học lệch: ",diem_2a[:,max])

    max2 = 0
    min2 = 0
    for i in range(0,diem_2a.shape[0]):
        if(diem_2a[i,:].std() > diem_2a[max2,:].std()):
            max2 = i 
        if(diem_2a[i,:].std() < diem_2a[min2,:].std()):
            min2 = i
    print("Môn học có điểm đồng đều nhất: [", min2, "]",sep="")
    print("Bảng điểm của môn học đồng đều: [",diem_2a[min2,:],"]",sep="")
    print("-----------------------------------------------------------------------")
    print("Môn học có điểm lệch nhất: [", max2, "]",sep="")
    print("Bảng điểm của môn học lệch: [",diem_2a[max2,:],"]",sep="")

yc1(diem_2a)
yc2(diem_2a)
yc3(diem_2a)

[[ 2.  4.  3.  7.  5.  6.  5.  6.  8.  9.  3.  6.  1.  9.  8.  7.  3.  3.  9.  5.]
 [ 3.  5.  3. 10.  9.  1.  9.  8.  3.  1.  6.  0.  7. 10.  8.  5.  2.  7.  7.  1.]
 [ 1. 10.  4.  9.  6.  9.  0.  2.  3.  1.  8.  6.  8.  4.  2.  9.  2.  9.  5.  0.]
 [ 6.  3.  0.  8.  3.  7.  7.  2.  6.  8.  7.  3.  4.  1.  5.  9.  1.  0.  2. 10.]
 [ 4.  3.  6.  7.  4.  5.  2.  6.  9.  4.  3.  9.  9.  4.  5.  7.  2. 10.  9.  4.]
 [ 2.  3.  8. 10.  4.  5.  9.  5.  4.  7. 10.  1.  8.  4.  3.  9.  6.  3.  6.  7.]
 [ 9.  9.  1. 10.  9.  9.  5.  9.  6.  3.  9.  5.  1. 10.  7. 10.  2.  8.  8.  1.]
 [ 8.  8.  7.  8.  6.  7.  7.  8.  6.  7.  8.  6.  7.  6.  8.  8.  7.  6.  8.  8.]
 [ 6.  7.  8.  9. 10.  9.  2.  2.  6.  1. 10.  9.  6.  3.  9.  5.  9.  8.  1.  1.]
 [ 7.  8.  7.  8.  6. 10. 10.  6.  8. 10.  8.  9.  8.  8.  5. 10.  8.  7.  8.  7.]]


Điểm TB của từng học sinh trong lớp:  [4.8 6.  4.7 8.6 6.2 6.8 5.6 5.4 5.9 5.1 7.2 5.4 5.9 5.9 6.  7.9 4.2 6.1 6.3 4.4]
-----------------------------------------------