In [1]:
import numpy as np
np.set_printoptions(linewidth=100)
data_numpy = np.loadtxt("Temp.txt", dtype=np.float64)
data_thongke = np.empty([3,7],dtype=np.float64)

#yc1
print(data_numpy)
print("Kích thước biến:", data_numpy.shape)
print("Số chiều của biến:", data_numpy.ndim)
print("Kiểu dữ liệu của các phần tử:", data_numpy.dtype)
print("Số phần tử:", data_numpy.size)

#yc2,3
print("\n-------THỐNG KÊ CHO CẢ 6 THÀNH PHỐ----------")
print("Nhiệt độ cao nhất:", data_numpy.max())
data_thongke[0,6] = data_numpy.max()
print("Nhiệt độ thấp nhất:", data_numpy.min())
data_thongke[2,6] = data_numpy.min()
print("Nhiệt độ trung bình:", data_numpy.mean())
data_thongke[1,6] = round(data_numpy.mean(),2)
print("--------------------------------------------")

for i in range(0, data_numpy.shape[1]):
    if(i == 0): print("1) Hà Nội")
    elif(i == 1): print("2) Vinh (Nghệ An)")
    elif(i == 2): print("3) Đà Nẵng")
    elif(i == 3): print("4) Nha Trang")
    elif(i == 4): print("5) TP Hồ Chí Minh")
    elif(i == 5): print("6) Cà Mau")
    print("Nhiệt độ cao nhất:", data_numpy[:,i].max())
    data_thongke[0,i] = data_numpy[:,i].max()
    print("Nhiệt độ thấp nhất:", data_numpy[:,i].min())
    data_thongke[2,i] = data_numpy[:,i].min()
    print("Nhiệt độ trung bình:", data_numpy[:,i].mean())
    data_thongke[1,i] = round(data_numpy[:,i].mean(),2)

#yc4
print(data_thongke)
print(type(data_thongke))
print('Kích thước:', data_thongke.shape)

f = open("thongke.txt", 'w')
f.write(str(data_thongke))
f.close()

[[25.65 24.79 24.01 25.06 25.48 24.97]
 [25.31 24.21 24.02 24.93 25.16 24.83]
 [25.05 23.73 23.89 24.79 24.8  24.55]
 ...
 [24.81 24.47 23.4  25.86 25.05 25.29]
 [23.97 24.22 22.95 25.74 24.92 24.87]
 [22.84 23.99 22.59 25.5  24.77 24.57]]
Kích thước biến: (192, 6)
Số chiều của biến: 2
Kiểu dữ liệu của các phần tử: float64
Số phần tử: 1152

-------THỐNG KÊ CHO CẢ 6 THÀNH PHỐ----------
Nhiệt độ cao nhất: 33.45
Nhiệt độ thấp nhất: 20.93
Nhiệt độ trung bình: 26.50222222222222
--------------------------------------------
1) Hà Nội
Nhiệt độ cao nhất: 33.45
Nhiệt độ thấp nhất: 21.68
Nhiệt độ trung bình: 27.71229166666667
2) Vinh (Nghệ An)
Nhiệt độ cao nhất: 32.57
Nhiệt độ thấp nhất: 22.6
Nhiệt độ trung bình: 26.719895833333336
3) Đà Nẵng
Nhiệt độ cao nhất: 29.88
Nhiệt độ thấp nhất: 20.93
Nhiệt độ trung bình: 25.522499999999997
4) Nha Trang
Nhiệt độ cao nhất: 28.68
Nhiệt độ thấp nhất: 24.5
Nhiệt độ trung bình: 26.166875000000005
5) TP Hồ Chí Minh
Nhiệt độ cao nhất: 31.06
Nhiệt độ thấp nhất: 2